<?php
declare(strict_types=1);
require_once __DIR__ . '/auth.php';
require_once __DIR__ . '/../config/config.php';
if (session_status() === PHP_SESSION_NONE) session_start();
function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function photoUrl(?string $name): string {
    $name=trim((string)$name);
    return $name==='' ? '/admin/assets/img/user-placeholder.svg' : '/admin/user_photo.php?name='.rawurlencode($name);
}
function fieldOptions(PDO $pdo,array $cfg): array {
    if (($cfg['type']??'')!=='select') return [];
    $table=(string)($cfg['table']??''); $column=(string)($cfg['column']??'');
    if (!preg_match('/^[A-Za-z0-9_]+$/',$table)||!preg_match('/^[A-Za-z0-9_]+$/',$column)) return [];
    try { return array_values(array_unique(array_map('strval',$pdo->query("SELECT DISTINCT `$column` FROM `$table` WHERE `$column` IS NOT NULL AND TRIM(`$column`)<>'' ORDER BY `$column`")->fetchAll(PDO::FETCH_COLUMN)))); }
    catch(Throwable){ return []; }
}
$userId=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT);
if(!$userId){ header('Location: /admin/users.php'); exit; }
$stmt=$pdo->prepare('SELECT * FROM users_profile WHERE Id=? LIMIT 1'); $stmt->execute([$userId]); $user=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$user){ http_response_code(404); exit('המשתמש לא נמצא'); }
$profileFields=require __DIR__.'/../profile_fields.php'; if(!is_array($profileFields)) $profileFields=[];
$stmt=$pdo->prepare('SELECT Pic_Num,Pic_Name,Pic_Title,Pic_Status_Str,Main_Pic FROM user_pics WHERE Id=? ORDER BY Main_Pic DESC,Pic_Num'); $stmt->execute([$userId]); $photos=$stmt->fetchAll(PDO::FETCH_ASSOC);
$mainPhoto=$photos[0]['Pic_Name']??null;
$age=null; if(!empty($user['DOB'])){ try{$age=(new DateTimeImmutable((string)$user['DOB']))->diff(new DateTimeImmutable('today'))->y;}catch(Throwable){} }
$lastSeen=trim((string)($user['last_seen']??'')); if($lastSeen===''&&!empty($user['Login_Date'])) $lastSeen=trim((string)$user['Login_Date'].' '.(string)($user['Login_Time']??''));
$right=[];$left=[];$options=[];
foreach($profileFields as $field=>$cfg){ if(($cfg['side']??'')==='right'){$right[$field]=$cfg;$options[$field]=fieldOptions($pdo,$cfg);} elseif(($cfg['side']??'')==='left')$left[$field]=$cfg; }
if(empty($_SESSION['admin_user_csrf'])) $_SESSION['admin_user_csrf']=bin2hex(random_bytes(32)); $csrf=(string)$_SESSION['admin_user_csrf'];
$msg=trim((string)($_GET['message']??'')); $type=($_GET['type']??'')==='error'?'error':'success';
$frozen=(int)($user['Is_Frozen']??0)===1; $verified=(int)($user['email_verified']??0)===1;
?>
<!DOCTYPE html><html lang="he" dir="rtl"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($user['Name']??'משתמש')?> | ניהול</title><link rel="stylesheet" href="/admin/assets/css/admin.css?v=4"><link rel="stylesheet" href="/admin/assets/css/admin-user-view.css?v=1"></head><body class="admin-page">
<aside class="admin-sidebar"><div class="admin-sidebar-logo"><span>❤</span><div><strong>LoveMatch</strong><small>ניהול האתר</small></div></div><nav class="admin-menu"><a href="/admin/index.php"><span>▦</span>דשבורד</a><a href="/admin/users.php" class="active"><span>♙</span>משתמשים</a><a href="/admin/photos.php"><span>▣</span>תמונות</a><a href="/admin/messages.php"><span>✉</span>הודעות</a><a href="/admin/reports.php"><span>⚑</span>דיווחים</a><a href="/admin/settings.php"><span>⚙</span>הגדרות</a></nav><a href="/admin/logout.php" class="admin-logout">יציאה</a></aside>
<main class="admin-main lm-page"><header class="admin-topbar"><div><h1><?=e($user['Name']??'ללא שם')?></h1><p>ניהול פרופיל #<?=(int)$userId?></p></div><div class="lm-actions"><a class="lm-btn light" href="/profile.php?id=<?=(int)$userId?>" target="_blank">צפייה באתר</a><a class="lm-btn light" href="/admin/users.php">חזרה</a></div></header>
<?php if($msg!==''):?><div class="lm-message <?=e($type)?>"><?=e($msg)?></div><?php endif;?>
<section class="lm-control"><div class="lm-statuses"><span class="lm-pill <?=$frozen?'danger':'success'?>">חשבון <?=$frozen?'קפוא':'פעיל'?></span><span class="lm-pill <?=$verified?'success':'muted'?>">אימייל <?=$verified?'מאומת':'לא מאומת'?></span><span class="lm-pill muted"><?=count($photos)?> תמונות</span></div><div class="lm-actions"><form action="/admin/user_action.php" method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="action" value="toggle_freeze"><button class="lm-btn <?=$frozen?'success':'warning'?>"><?=$frozen?'הפעל פרופיל':'הקפא פרופיל'?></button></form><form action="/admin/user_action.php" method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="action" value="toggle_email_verified"><button class="lm-btn primary"><?=$verified?'בטל אימות':'אמת אימייל'?></button></form></div></section>
<section class="lm-layout"><aside class="lm-side"><div class="lm-card lm-main-card"><div class="lm-main-img"><img src="<?=e(photoUrl($mainPhoto))?>" onerror="this.src='/admin/assets/img/user-placeholder.svg'" alt=""></div><h2><?=e($user['Name']??'ללא שם')?><?php if($age!==null):?>, <?=(int)$age?><?php endif;?></h2><p><?=e($user['Place_Str']??'')?> <?=!empty($user['Zone_Str'])?'• '.e($user['Zone_Str']):''?></p><button class="lm-edit" data-toggle="basic">✎ עריכת פרטים בסיסיים</button>
<form id="basic" hidden class="lm-editor" action="/admin/user_update.php" method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="action" value="save_basic"><?php foreach(['Name'=>'שם','Email'=>'אימייל','DOB'=>'תאריך לידה','Gender_Str'=>'מין','Zone_Str'=>'אזור','Place_Str'=>'עיר'] as $f=>$label):?><label><span><?=e($label)?></span><input type="<?=$f==='DOB'?'date':($f==='Email'?'email':'text')?>" name="<?=e($f)?>" value="<?=e($user[$f]??'')?>"></label><?php endforeach;?><div class="lm-actions"><button class="lm-btn primary">שמור</button><button type="button" class="lm-btn light" data-close="basic">ביטול</button></div></form>
<div class="lm-facts"><?php foreach($right as $field=>$cfg):?><?php $val=(($cfg['type']??'')==='computed'&&$field==='Age_Computed')?(string)($age??''):trim((string)($user[$field]??''));?><div><span><?=e($cfg['label']??$field)?>:</span><strong><?=$val!==''?e($val):'לא מולא'?></strong></div><?php endforeach;?></div><button class="lm-edit" data-toggle="rightEdit">✎ עריכת פרטים נוספים</button>
<form id="rightEdit" hidden class="lm-editor" action="/admin/user_update.php" method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="action" value="save_fields"><?php foreach($right as $field=>$cfg): if(($cfg['type']??'')==='computed')continue; $val=trim((string)($user[$field]??''));?><label><span><?=e($cfg['label']??$field)?></span><?php if(!empty($options[$field])):?><select name="fields[<?=e($field)?>]"><option value="">בחר</option><?php foreach($options[$field] as $op):?><option value="<?=e($op)?>" <?=$op===$val?'selected':''?>><?=e($op)?></option><?php endforeach;?></select><?php else:?><input name="fields[<?=e($field)?>]" value="<?=e($val)?>"><?php endif;?></label><?php endforeach;?><div class="lm-actions"><button class="lm-btn primary">שמור</button><button type="button" class="lm-btn light" data-close="rightEdit">ביטול</button></div></form>
<div class="lm-mini"><span>הרשמה: <b><?=e($user['Open_Date']??'—')?></b></span><span>התחברות: <b><?=e($lastSeen?:'—')?></b></span></div></div></aside>
<div class="lm-content"><?php foreach($left as $field=>$cfg): $val=trim((string)($user[$field]??''));?><article class="lm-card lm-text"><header><h3><?=e($cfg['label']??$field)?></h3><button class="lm-edit" data-toggle="edit-<?=e($field)?>">✎ עריכה</button></header><div class="lm-copy <?=$val===''?'empty':''?>"><?=$val!==''?nl2br(e($val)):'לא מולא'?></div><form id="edit-<?=e($field)?>" hidden class="lm-editor" action="/admin/user_update.php" method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="action" value="save_field"><input type="hidden" name="field" value="<?=e($field)?>"><textarea name="value" rows="6"><?=e($val)?></textarea><div class="lm-actions"><button class="lm-btn primary">שמור</button><button type="button" class="lm-btn light" data-close="edit-<?=e($field)?>">ביטול</button></div></form></article><?php endforeach;?>
<article class="lm-card lm-gallery"><header><div><h3>גלריית תמונות</h3><p><?=count($photos)?> תמונות</p></div></header><div class="lm-grid"><?php foreach($photos as $i=>$p): $pic=(int)$p['Pic_Num'];$url=photoUrl($p['Pic_Name']??null);$main=(int)($p['Main_Pic']??0)===1;?><div class="lm-photo"><button type="button" data-image="<?=e($url)?>"><img src="<?=e($url)?>" alt=""></button><?php if($main):?><span class="lm-main">ראשית</span><?php endif;?><div class="lm-photo-actions"><?php if(!$main):?><form action="/admin/user_photo_action.php" method="post"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="pic_num" value="<?=$pic?>"><input type="hidden" name="action" value="set_main"><button>קבע כראשית</button></form><?php endif;?><form action="/admin/user_photo_action.php" method="post" onsubmit="return confirm('למחוק את התמונה?')"><input type="hidden" name="csrf_token" value="<?=e($csrf)?>"><input type="hidden" name="user_id" value="<?=(int)$userId?>"><input type="hidden" name="pic_num" value="<?=$pic?>"><input type="hidden" name="action" value="delete"><button class="del">מחק</button></form></div></div><?php endforeach;?></div></article></div></section></main>
<div id="modal" class="lm-modal" hidden><button type="button">×</button><img src="" alt=""></div>
<script>document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const x=document.getElementById(b.dataset.toggle);if(x)x.hidden=!x.hidden});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{const x=document.getElementById(b.dataset.close);if(x)x.hidden=true});const m=document.getElementById('modal'),mi=m.querySelector('img');document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{mi.src=b.dataset.image;m.hidden=false});m.querySelector('button').onclick=()=>{m.hidden=true;mi.src=''};m.onclick=e=>{if(e.target===m){m.hidden=true;mi.src=''}};</script></body></html>
